[2023-11-20T21:30:03.782+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet1.maj manual__2023-11-20T21:28:23.009540+00:00 [queued]>
[2023-11-20T21:30:03.956+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet1.maj manual__2023-11-20T21:28:23.009540+00:00 [queued]>
[2023-11-20T21:30:03.959+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-20T21:30:04.077+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): maj> on 2023-11-20 21:28:23.009540+00:00
[2023-11-20T21:30:04.110+0000] {standard_task_runner.py:57} INFO - Started process 1962 to run task
[2023-11-20T21:30:04.123+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet1', 'maj', 'manual__2023-11-20T21:28:23.009540+00:00', '--job-id', '343', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmpv_soz_29']
[2023-11-20T21:30:04.127+0000] {standard_task_runner.py:85} INFO - Job 343: Subtask maj
[2023-11-20T21:30:04.263+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet1.maj manual__2023-11-20T21:28:23.009540+00:00 [running]> on host b36ebcee5948
[2023-11-20T21:30:04.440+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet1' AIRFLOW_CTX_TASK_ID='maj' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T21:28:23.009540+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-20T21:28:23.009540+00:00'
[2023-11-20T21:30:04.445+0000] {sql.py:274} INFO - Executing: -- Ajout de la clé primaire à la table "Urgences"
ALTER TABLE "Urgences"
ADD PRIMARY KEY (dep, sursaud_cl_age_corona);

-- Ajout des clés étrangères à la table "Urgences"
ALTER TABLE "Urgences"
ADD CONSTRAINT fk_dep FOREIGN KEY (dep) REFERENCES "Departements"(num_dep);

ALTER TABLE "Urgences"
ADD CONSTRAINT fk_age FOREIGN KEY (sursaud_cl_age_corona) REFERENCES "Age"(Code_age);

-- Ajout de la clé primaire à la table "Departements"
ALTER TABLE "Departements"
ADD PRIMARY KEY (num_dep);

-- Ajout de la clé primaire à la table "Age"
ALTER TABLE "Age"
ADD PRIMARY KEY (Code_age);
[2023-11-20T21:30:04.460+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-20T21:30:04.480+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-20T21:30:04.541+0000] {sql.py:418} INFO - Running statement: -- Ajout de la clé primaire à la table "Urgences"
ALTER TABLE "Urgences"
ADD PRIMARY KEY (dep, sursaud_cl_age_corona);

-- Ajout des clés étrangères à la table "Urgences"
ALTER TABLE "Urgences"
ADD CONSTRAINT fk_dep FOREIGN KEY (dep) REFERENCES "Departements"(num_dep);

ALTER TABLE "Urgences"
ADD CONSTRAINT fk_age FOREIGN KEY (sursaud_cl_age_corona) REFERENCES "Age"(Code_age);

-- Ajout de la clé primaire à la table "Departements"
ALTER TABLE "Departements"
ADD PRIMARY KEY (num_dep);

-- Ajout de la clé primaire à la table "Age"
ALTER TABLE "Age"
ADD PRIMARY KEY (Code_age);, parameters: None
[2023-11-20T21:30:05.034+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: could not create unique index "Urgences_pkey"
DETAIL:  Key (dep, sursaud_cl_age_corona)=(35.0, 1) is duplicated.

[2023-11-20T21:30:05.066+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet1, task_id=maj, execution_date=20231120T212823, start_date=20231120T213003, end_date=20231120T213005
[2023-11-20T21:30:05.102+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 343 for task maj (could not create unique index "Urgences_pkey"
DETAIL:  Key (dep, sursaud_cl_age_corona)=(35.0, 1) is duplicated.
; 1962)
[2023-11-20T21:30:05.149+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T21:30:05.202+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
