[2023-11-11T21:48:24.280+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: A.Extract manual__2023-11-11T21:48:22.470522+00:00 [queued]>
[2023-11-11T21:48:24.289+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: A.Extract manual__2023-11-11T21:48:22.470522+00:00 [queued]>
[2023-11-11T21:48:24.290+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-11T21:48:24.303+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Extract> on 2023-11-11 21:48:22.470522+00:00
[2023-11-11T21:48:24.309+0000] {standard_task_runner.py:57} INFO - Started process 27021 to run task
[2023-11-11T21:48:24.312+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'A', 'Extract', 'manual__2023-11-11T21:48:22.470522+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmppa4r1r51']
[2023-11-11T21:48:24.314+0000] {standard_task_runner.py:85} INFO - Job 87: Subtask Extract
[2023-11-11T21:48:24.363+0000] {task_command.py:416} INFO - Running <TaskInstance: A.Extract manual__2023-11-11T21:48:22.470522+00:00 [running]> on host fb26c01043df
[2023-11-11T21:48:24.439+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='A' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T21:48:22.470522+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-11T21:48:22.470522+00:00'
[2023-11-11T21:48:24.443+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-11T21:48:24.444+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --keepalive-time 6000 -o ${AIRFLOW_HOME}/data/valeurs.csv file:///Users/celinahamzaoui/Desktop/Cours_Sup_de_vinci/Datawarehouse/TP3/TP_Airflow/data/code-tranches-dage-donnees-urgences.csv']
[2023-11-11T21:48:24.459+0000] {subprocess.py:86} INFO - Output:
[2023-11-11T21:48:24.468+0000] {subprocess.py:93} INFO - curl: (37) Couldn't open file /Users/celinahamzaoui/Desktop/Cours_Sup_de_vinci/Datawarehouse/TP3/TP_Airflow/data/code-tranches-dage-donnees-urgences.csv
[2023-11-11T21:48:24.469+0000] {subprocess.py:97} INFO - Command exited with return code 37
[2023-11-11T21:48:24.481+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 37.
[2023-11-11T21:48:24.485+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=A, task_id=Extract, execution_date=20231111T214822, start_date=20231111T214824, end_date=20231111T214824
[2023-11-11T21:48:24.497+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 87 for task Extract (Bash command failed. The command returned a non-zero exit code 37.; 27021)
[2023-11-11T21:48:24.525+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-11T21:48:24.547+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
