[2023-11-23T11:50:04.325+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-23T11:49:59.169215+00:00 [queued]>
[2023-11-23T11:50:04.339+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-23T11:49:59.169215+00:00 [queued]>
[2023-11-23T11:50:04.340+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T11:50:04.357+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-23 11:49:59.169215+00:00
[2023-11-23T11:50:04.365+0000] {standard_task_runner.py:57} INFO - Started process 2489 to run task
[2023-11-23T11:50:04.370+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet1', 'Extract', 'manual__2023-11-23T11:49:59.169215+00:00', '--job-id', '562', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmp10k23chn']
[2023-11-23T11:50:04.372+0000] {standard_task_runner.py:85} INFO - Job 562: Subtask Extract
[2023-11-23T11:50:04.435+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet1.Extract manual__2023-11-23T11:49:59.169215+00:00 [running]> on host b36ebcee5948
[2023-11-23T11:50:04.539+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet1' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T11:49:59.169215+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T11:49:59.169215+00:00'
[2023-11-23T11:50:04.812+0000] {warnings.py:109} WARNING - /opt/***/dags/Projet.py:17: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_urgences,  delimiter=';' )

[2023-11-23T11:50:05.552+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Projet.py", line 50, in extract_data
    df_departements = df_departements.append(nouvelle_ligne, ignore_index=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
[2023-11-23T11:50:05.569+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet1, task_id=Extract, execution_date=20231123T114959, start_date=20231123T115004, end_date=20231123T115005
[2023-11-23T11:50:05.585+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 562 for task Extract ('DataFrame' object has no attribute 'append'; 2489)
[2023-11-23T11:50:05.633+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T11:50:05.658+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
