[2023-11-23T10:06:26.791+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-23T10:06:23.014700+00:00 [queued]>
[2023-11-23T10:06:26.802+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-23T10:06:23.014700+00:00 [queued]>
[2023-11-23T10:06:26.802+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T10:06:26.816+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-23 10:06:23.014700+00:00
[2023-11-23T10:06:26.821+0000] {standard_task_runner.py:57} INFO - Started process 677 to run task
[2023-11-23T10:06:26.824+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet1', 'Extract', 'manual__2023-11-23T10:06:23.014700+00:00', '--job-id', '471', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmpc_qk9c24']
[2023-11-23T10:06:26.826+0000] {standard_task_runner.py:85} INFO - Job 471: Subtask Extract
[2023-11-23T10:06:26.873+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet1.Extract manual__2023-11-23T10:06:23.014700+00:00 [running]> on host b36ebcee5948
[2023-11-23T10:06:26.953+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet1' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T10:06:23.014700+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T10:06:23.014700+00:00'
[2023-11-23T10:06:27.184+0000] {warnings.py:109} WARNING - /opt/***/dags/Projet.py:17: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_urgences,  delimiter=';' )

[2023-11-23T10:06:27.839+0000] {logging_mixin.py:151} INFO - 101
[2023-11-23T10:06:27.841+0000] {logging_mixin.py:151} INFO - 99
[2023-11-23T10:06:27.854+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-23T10:06:27.862+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE Age RESTART IDENTITY CASCADE, parameters: None
[2023-11-23T10:06:27.865+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Projet.py", line 116, in extract_data
    postgres_sql_upload.run("TRUNCATE TABLE Age RESTART IDENTITY CASCADE")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "age" does not exist

[2023-11-23T10:06:27.875+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet1, task_id=Extract, execution_date=20231123T100623, start_date=20231123T100626, end_date=20231123T100627
[2023-11-23T10:06:27.887+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 471 for task Extract (relation "age" does not exist
; 677)
[2023-11-23T10:06:27.923+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T10:06:27.941+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
