[2023-11-23T11:20:38.056+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-23T11:20:33.908018+00:00 [queued]>
[2023-11-23T11:20:38.066+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-23T11:20:33.908018+00:00 [queued]>
[2023-11-23T11:20:38.067+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T11:20:38.081+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-23 11:20:33.908018+00:00
[2023-11-23T11:20:38.086+0000] {standard_task_runner.py:57} INFO - Started process 1978 to run task
[2023-11-23T11:20:38.089+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet1', 'Extract', 'manual__2023-11-23T11:20:33.908018+00:00', '--job-id', '536', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmp8trwgves']
[2023-11-23T11:20:38.091+0000] {standard_task_runner.py:85} INFO - Job 536: Subtask Extract
[2023-11-23T11:20:38.145+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet1.Extract manual__2023-11-23T11:20:33.908018+00:00 [running]> on host b36ebcee5948
[2023-11-23T11:20:38.227+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet1' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T11:20:33.908018+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T11:20:33.908018+00:00'
[2023-11-23T11:20:38.432+0000] {warnings.py:109} WARNING - /opt/***/dags/Projet.py:17: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_urgences,  delimiter=';' )

[2023-11-23T11:20:38.782+0000] {logging_mixin.py:151} INFO - 101
[2023-11-23T11:20:38.785+0000] {logging_mixin.py:151} INFO - 99
[2023-11-23T11:20:38.789+0000] {logging_mixin.py:151} INFO - Index(['Code tranches d'age', 'Age'], dtype='object')
[2023-11-23T11:20:38.790+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Projet.py", line 94, in extract_data
    print(df_age.columns.dtypes)
AttributeError: 'Index' object has no attribute 'dtypes'
[2023-11-23T11:20:38.800+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet1, task_id=Extract, execution_date=20231123T112033, start_date=20231123T112038, end_date=20231123T112038
[2023-11-23T11:20:38.818+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 536 for task Extract ('Index' object has no attribute 'dtypes'; 1978)
[2023-11-23T11:20:38.866+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T11:20:38.885+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
