[2023-11-23T11:37:33.946+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-23T11:37:30.262733+00:00 [queued]>
[2023-11-23T11:37:33.963+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-23T11:37:30.262733+00:00 [queued]>
[2023-11-23T11:37:33.965+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T11:37:33.985+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-23 11:37:30.262733+00:00
[2023-11-23T11:37:33.990+0000] {standard_task_runner.py:57} INFO - Started process 2290 to run task
[2023-11-23T11:37:33.994+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet1', 'Extract', 'manual__2023-11-23T11:37:30.262733+00:00', '--job-id', '554', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmp9paxs8wl']
[2023-11-23T11:37:33.996+0000] {standard_task_runner.py:85} INFO - Job 554: Subtask Extract
[2023-11-23T11:37:34.078+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet1.Extract manual__2023-11-23T11:37:30.262733+00:00 [running]> on host b36ebcee5948
[2023-11-23T11:37:34.164+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet1' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T11:37:30.262733+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T11:37:30.262733+00:00'
[2023-11-23T11:37:34.426+0000] {warnings.py:109} WARNING - /opt/***/dags/Projet.py:17: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_urgences,  delimiter=';' )

[2023-11-23T11:37:35.042+0000] {logging_mixin.py:151} INFO - 101
[2023-11-23T11:37:35.045+0000] {logging_mixin.py:151} INFO - 99
[2023-11-23T11:37:35.064+0000] {logging_mixin.py:151} INFO -    Code tranches d'age             Age
0                    0       tous Ã¢ges
1                    1         0-4 ans
2                    2        5-14 ans
3                    3       15-44 ans
4                    4       45-64 ans
5                    5       65-74 ans
6                    6  75 ans ou plus
[2023-11-23T11:37:35.065+0000] {logging_mixin.py:151} INFO - Index(['Code tranches d'age', 'Age'], dtype='object')
[2023-11-23T11:37:35.068+0000] {logging_mixin.py:151} INFO - Index(['code_age', 'agess'], dtype='object')
[2023-11-23T11:37:35.068+0000] {logging_mixin.py:151} INFO - zmmmmmmarr 
[2023-11-23T11:37:35.079+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-23T11:37:35.146+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-23T11:37:35.175+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-23T11:37:35.531+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "date_de_passage" of relation "Urgences" does not exist
LINE 1: INSERT INTO "Urgences" (dep, date_de_passage, sursaud_cl_age...
                                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Projet.py", line 117, in extract_data
    df_urgences.to_sql('Urgences', postgres_sql_upload.get_sqlalchemy_engine(), if_exists='append', chunksize=1000, index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1920, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1470, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1461, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1023, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 929, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "date_de_passage" of relation "Urgences" does not exist
LINE 1: INSERT INTO "Urgences" (dep, date_de_passage, sursaud_cl_age...
                                     ^

[SQL: INSERT INTO "Urgences" (dep, date_de_passage, sursaud_cl_age_corona, nbre_pass_corona, nbre_pass_tot, nbre_hospit_corona, nbre_pass_corona_h, nbre_pass_corona_f, nbre_pass_tot_h, nbre_pass_tot_f, nbre_hospit_corona_h, nbre_hospit_corona_f, nbre_acte_corona, nbre_acte_tot, nbre_acte_corona_h, nbre_acte_corona_f, nbre_acte_tot_h, nbre_acte_tot_f) VALUES (%(dep)s, %(date_de_passage)s, %(sursaud_cl_age_corona)s, %(nbre_pass_corona)s, %(nbre_pass_tot)s, %(nbre_hospit_corona)s, %(nbre_pass_corona_h)s, %(nbre_pass_corona_f)s, %(nbre_pass_tot_h)s, %(nbre_pass_tot_f)s, %(nbre_hospit_corona_h)s, %(nbre_hospit_corona_f)s, %(nbre_acte_corona)s, %(nbre_acte_tot)s, %(nbre_acte_corona_h)s, %(nbre_acte_corona_f)s, %(nbre_acte_tot_h)s, %(nbre_acte_tot_f)s)]
[parameters: ({'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 0, 'nbre_pass_corona': 9.0, 'nbre_pass_tot': 435.0, 'nbre_hospit_corona': 4.0, 'nbre_pass_corona_h': 6.0, 'nbre_pass_corona_f': 3.0, 'nbre_pass_tot_h': 219.0, 'nbre_pass_tot_f': 216.0, 'nbre_hospit_corona_h': 1.0, 'nbre_hospit_corona_f': 3.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 1, 'nbre_pass_corona': 0.0, 'nbre_pass_tot': 58.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 2, 'nbre_pass_corona': 0.0, 'nbre_pass_tot': 30.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 3, 'nbre_pass_corona': 1.0, 'nbre_pass_tot': 138.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 4, 'nbre_pass_corona': 1.0, 'nbre_pass_tot': 88.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 5, 'nbre_pass_corona': 1.0, 'nbre_pass_tot': 45.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 6, 'nbre_pass_corona': 6.0, 'nbre_pass_tot': 75.0, 'nbre_hospit_corona': 4.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 27, 0, 0), 'sursaud_cl_age_corona': 0, 'nbre_pass_corona': 6.0, 'nbre_pass_tot': 452.0, 'nbre_hospit_corona': 4.0, 'nbre_pass_corona_h': 1.0, 'nbre_pass_corona_f': 5.0, 'nbre_pass_tot_h': 236.0, 'nbre_pass_tot_f': 216.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 4.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}  ... displaying 10 of 1000 total bound parameter sets ...  {'dep': 1.0, 'date_de_passage': datetime.datetime(2023, 5, 17, 0, 0), 'sursaud_cl_age_corona': 4, 'nbre_pass_corona': 3.0, 'nbre_pass_tot': 84.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2023, 5, 17, 0, 0), 'sursaud_cl_age_corona': 5, 'nbre_pass_corona': 0.0, 'nbre_pass_tot': 40.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-11-23T11:37:35.557+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet1, task_id=Extract, execution_date=20231123T113730, start_date=20231123T113733, end_date=20231123T113735
[2023-11-23T11:37:35.572+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 554 for task Extract ((psycopg2.errors.UndefinedColumn) column "date_de_passage" of relation "Urgences" does not exist
LINE 1: INSERT INTO "Urgences" (dep, date_de_passage, sursaud_cl_age...
                                     ^

[SQL: INSERT INTO "Urgences" (dep, date_de_passage, sursaud_cl_age_corona, nbre_pass_corona, nbre_pass_tot, nbre_hospit_corona, nbre_pass_corona_h, nbre_pass_corona_f, nbre_pass_tot_h, nbre_pass_tot_f, nbre_hospit_corona_h, nbre_hospit_corona_f, nbre_acte_corona, nbre_acte_tot, nbre_acte_corona_h, nbre_acte_corona_f, nbre_acte_tot_h, nbre_acte_tot_f) VALUES (%(dep)s, %(date_de_passage)s, %(sursaud_cl_age_corona)s, %(nbre_pass_corona)s, %(nbre_pass_tot)s, %(nbre_hospit_corona)s, %(nbre_pass_corona_h)s, %(nbre_pass_corona_f)s, %(nbre_pass_tot_h)s, %(nbre_pass_tot_f)s, %(nbre_hospit_corona_h)s, %(nbre_hospit_corona_f)s, %(nbre_acte_corona)s, %(nbre_acte_tot)s, %(nbre_acte_corona_h)s, %(nbre_acte_corona_f)s, %(nbre_acte_tot_h)s, %(nbre_acte_tot_f)s)]
[parameters: ({'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 0, 'nbre_pass_corona': 9.0, 'nbre_pass_tot': 435.0, 'nbre_hospit_corona': 4.0, 'nbre_pass_corona_h': 6.0, 'nbre_pass_corona_f': 3.0, 'nbre_pass_tot_h': 219.0, 'nbre_pass_tot_f': 216.0, 'nbre_hospit_corona_h': 1.0, 'nbre_hospit_corona_f': 3.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 1, 'nbre_pass_corona': 0.0, 'nbre_pass_tot': 58.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 2, 'nbre_pass_corona': 0.0, 'nbre_pass_tot': 30.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 3, 'nbre_pass_corona': 1.0, 'nbre_pass_tot': 138.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 4, 'nbre_pass_corona': 1.0, 'nbre_pass_tot': 88.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 5, 'nbre_pass_corona': 1.0, 'nbre_pass_tot': 45.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 26, 0, 0), 'sursaud_cl_age_corona': 6, 'nbre_pass_corona': 6.0, 'nbre_pass_tot': 75.0, 'nbre_hospit_corona': 4.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2022, 12, 27, 0, 0), 'sursaud_cl_age_corona': 0, 'nbre_pass_corona': 6.0, 'nbre_pass_tot': 452.0, 'nbre_hospit_corona': 4.0, 'nbre_pass_corona_h': 1.0, 'nbre_pass_corona_f': 5.0, 'nbre_pass_tot_h': 236.0, 'nbre_pass_tot_f': 216.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 4.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}  ... displaying 10 of 1000 total bound parameter sets ...  {'dep': 1.0, 'date_de_passage': datetime.datetime(2023, 5, 17, 0, 0), 'sursaud_cl_age_corona': 4, 'nbre_pass_corona': 3.0, 'nbre_pass_tot': 84.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0}, {'dep': 1.0, 'date_de_passage': datetime.datetime(2023, 5, 17, 0, 0), 'sursaud_cl_age_corona': 5, 'nbre_pass_corona': 0.0, 'nbre_pass_tot': 40.0, 'nbre_hospit_corona': 0.0, 'nbre_pass_corona_h': 0.0, 'nbre_pass_corona_f': 0.0, 'nbre_pass_tot_h': 0.0, 'nbre_pass_tot_f': 0.0, 'nbre_hospit_corona_h': 0.0, 'nbre_hospit_corona_f': 0.0, 'nbre_acte_corona': 0.0, 'nbre_acte_tot': 0.0, 'nbre_acte_corona_h': 0.0, 'nbre_acte_corona_f': 0.0, 'nbre_acte_tot_h': 0.0, 'nbre_acte_tot_f': 0.0})]
(Background on this error at: https://sqlalche.me/e/14/f405); 2290)
[2023-11-23T11:37:35.617+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T11:37:35.637+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
