[2023-11-11T14:18:33.767+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ProjetETL.telechargement_fichier1 manual__2023-11-11T14:18:31.331556+00:00 [queued]>
[2023-11-11T14:18:33.778+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ProjetETL.telechargement_fichier1 manual__2023-11-11T14:18:31.331556+00:00 [queued]>
[2023-11-11T14:18:33.779+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-11T14:18:33.793+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): telechargement_fichier1> on 2023-11-11 14:18:31.331556+00:00
[2023-11-11T14:18:33.799+0000] {standard_task_runner.py:57} INFO - Started process 22934 to run task
[2023-11-11T14:18:33.802+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ProjetETL', 'telechargement_fichier1', 'manual__2023-11-11T14:18:31.331556+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmpg14sbjpg']
[2023-11-11T14:18:33.809+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask telechargement_fichier1
[2023-11-11T14:18:33.860+0000] {task_command.py:416} INFO - Running <TaskInstance: ProjetETL.telechargement_fichier1 manual__2023-11-11T14:18:31.331556+00:00 [running]> on host fb26c01043df
[2023-11-11T14:18:33.935+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ProjetETL' AIRFLOW_CTX_TASK_ID='telechargement_fichier1' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T14:18:31.331556+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-11T14:18:31.331556+00:00'
[2023-11-11T14:18:33.938+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-11T14:18:33.939+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --keepalive-time 600 -o $AIRFLOW_HOME/data/code-tranches-dage-donnees-urgences.csv https://votre_url1.csv']
[2023-11-11T14:18:33.951+0000] {subprocess.py:86} INFO - Output:
[2023-11-11T14:18:33.962+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-11-11T14:18:33.963+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-11-11T14:18:34.095+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: votre_url1.csv
[2023-11-11T14:18:34.096+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2023-11-11T14:18:34.110+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2023-11-11T14:18:34.114+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ProjetETL, task_id=telechargement_fichier1, execution_date=20231111T141831, start_date=20231111T141833, end_date=20231111T141834
[2023-11-11T14:18:34.125+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 47 for task telechargement_fichier1 (Bash command failed. The command returned a non-zero exit code 6.; 22934)
[2023-11-11T14:18:34.136+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-11T14:18:34.164+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
